// Code generated by protoc-gen-go.
// source: src/skywalker/message/request.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	src/skywalker/message/request.proto
	src/skywalker/message/response.proto

It has these top-level messages:
	StatusRequest
	StartRequest
	StopRequest
	InfoRequest
	Request
	Error
	StatusResponse
	StartResponse
	StopResponse
	Response
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_STATUS RequestType = 1
	RequestType_START  RequestType = 2
	RequestType_STOP   RequestType = 3
	RequestType_INFO   RequestType = 4
)

var RequestType_name = map[int32]string{
	1: "STATUS",
	2: "START",
	3: "STOP",
	4: "INFO",
}
var RequestType_value = map[string]int32{
	"STATUS": 1,
	"START":  2,
	"STOP":   3,
	"INFO":   4,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusRequest struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type StartRequest struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StartRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type StopRequest struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StopRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type InfoRequest struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *InfoRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type Request struct {
	Version          *int32         `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type             *RequestType   `protobuf:"varint,2,req,name=type,enum=message.RequestType" json:"type,omitempty"`
	Status           *StatusRequest `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Start            *StartRequest  `protobuf:"bytes,4,opt,name=start" json:"start,omitempty"`
	Stop             *StopRequest   `protobuf:"bytes,5,opt,name=stop" json:"stop,omitempty"`
	Info             *InfoRequest   `protobuf:"bytes,6,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Request) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Request) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_STATUS
}

func (m *Request) GetStatus() *StatusRequest {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Request) GetStart() *StartRequest {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Request) GetStop() *StopRequest {
	if m != nil {
		return m.Stop
	}
	return nil
}

func (m *Request) GetInfo() *InfoRequest {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "message.StatusRequest")
	proto.RegisterType((*StartRequest)(nil), "message.StartRequest")
	proto.RegisterType((*StopRequest)(nil), "message.StopRequest")
	proto.RegisterType((*InfoRequest)(nil), "message.InfoRequest")
	proto.RegisterType((*Request)(nil), "message.Request")
	proto.RegisterEnum("message.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("src/skywalker/message/request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x8f, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0xe9, 0x9a, 0xb6, 0xee, 0x75, 0x6a, 0x09, 0x53, 0x02, 0x2a, 0x8c, 0x2a, 0x52, 0x3c,
	0xb4, 0xb0, 0x93, 0x57, 0x2f, 0xc2, 0x2e, 0x4e, 0x96, 0xf8, 0x03, 0x8a, 0x44, 0x19, 0x73, 0x4d,
	0xcd, 0xcb, 0x94, 0xfd, 0x4f, 0x7f, 0x90, 0x6f, 0xb5, 0xba, 0x2a, 0xf3, 0xf6, 0x92, 0xef, 0x0b,
	0x79, 0x1f, 0x9c, 0xa3, 0x7d, 0x2c, 0x70, 0xb1, 0x7e, 0x2f, 0x5f, 0x16, 0xda, 0x16, 0x4b, 0x8d,
	0x58, 0x3e, 0xeb, 0xc2, 0xea, 0xd7, 0x95, 0x46, 0x97, 0xd7, 0xd6, 0x38, 0xc3, 0xa3, 0xf6, 0x3a,
	0x3d, 0x83, 0x7d, 0xe9, 0x4a, 0xb7, 0xc2, 0xd9, 0x17, 0xe7, 0x03, 0x60, 0x55, 0xb9, 0xd4, 0xc2,
	0x1b, 0xf9, 0x59, 0x3f, 0x3d, 0x85, 0x01, 0x61, 0xeb, 0x76, 0xd3, 0x13, 0x88, 0xa5, 0x33, 0xf5,
	0xbf, 0x70, 0x52, 0x3d, 0x99, 0xdd, 0xf0, 0xc3, 0x83, 0xe8, 0x9b, 0x1c, 0x42, 0xf4, 0xa6, 0x2d,
	0xce, 0x4d, 0x45, 0xb0, 0x97, 0x05, 0x3c, 0x05, 0xe6, 0xd6, 0xb5, 0x16, 0x3d, 0x3a, 0x1d, 0x8c,
	0x87, 0x79, 0xbb, 0x6b, 0xde, 0x3e, 0x50, 0xc4, 0xf8, 0x25, 0x84, 0xd8, 0xec, 0x2d, 0xfc, 0x91,
	0x97, 0xc5, 0xe3, 0xe3, 0x1f, 0xeb, 0x77, 0xce, 0x05, 0x04, 0xb8, 0x09, 0x10, 0xac, 0xd1, 0x8e,
	0xba, 0xda, 0x36, 0x8b, 0x7e, 0x44, 0x0a, 0x11, 0x41, 0x23, 0x0d, 0x3b, 0xd2, 0xb6, 0x8e, 0x9c,
	0x39, 0xf5, 0x88, 0xf0, 0x8f, 0xd3, 0x89, 0xbc, 0xba, 0x86, 0xb8, 0xbb, 0x24, 0x40, 0x28, 0xd5,
	0x8d, 0x7a, 0x90, 0x89, 0xc7, 0xfb, 0x10, 0xd0, 0x3c, 0x53, 0x49, 0x8f, 0xef, 0x01, 0x93, 0x6a,
	0x7a, 0x9f, 0xf8, 0x9b, 0x69, 0x72, 0x77, 0x3b, 0x4d, 0xd8, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x98, 0xf7, 0x33, 0xcd, 0xb6, 0x01, 0x00, 0x00,
}
