// Code generated by protoc-gen-go.
// source: src/skywalker/message/response.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StatusResponse_Status int32

const (
	StatusResponse_STOPPED StatusResponse_Status = 1
	StatusResponse_RUNNING StatusResponse_Status = 2
	StatusResponse_ERROR   StatusResponse_Status = 3
)

var StatusResponse_Status_name = map[int32]string{
	1: "STOPPED",
	2: "RUNNING",
	3: "ERROR",
}
var StatusResponse_Status_value = map[string]int32{
	"STOPPED": 1,
	"RUNNING": 2,
	"ERROR":   3,
}

func (x StatusResponse_Status) Enum() *StatusResponse_Status {
	p := new(StatusResponse_Status)
	*p = x
	return p
}
func (x StatusResponse_Status) String() string {
	return proto.EnumName(StatusResponse_Status_name, int32(x))
}
func (x *StatusResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StatusResponse_Status_value, data, "StatusResponse_Status")
	if err != nil {
		return err
	}
	*x = StatusResponse_Status(value)
	return nil
}
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

type StartResponse_Status int32

const (
	StartResponse_STARTED StartResponse_Status = 1
	StartResponse_ERROR   StartResponse_Status = 2
	StartResponse_RUNNING StartResponse_Status = 3
)

var StartResponse_Status_name = map[int32]string{
	1: "STARTED",
	2: "ERROR",
	3: "RUNNING",
}
var StartResponse_Status_value = map[string]int32{
	"STARTED": 1,
	"ERROR":   2,
	"RUNNING": 3,
}

func (x StartResponse_Status) Enum() *StartResponse_Status {
	p := new(StartResponse_Status)
	*p = x
	return p
}
func (x StartResponse_Status) String() string {
	return proto.EnumName(StartResponse_Status_name, int32(x))
}
func (x *StartResponse_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StartResponse_Status_value, data, "StartResponse_Status")
	if err != nil {
		return err
	}
	*x = StartResponse_Status(value)
	return nil
}
func (StartResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

// 出错
type Error struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Error) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

// status 命令的返回结果
type StatusResponse struct {
	Data             []*StatusResponse_Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StatusResponse) GetData() []*StatusResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StatusResponse_Data struct {
	Name             *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Cname            *string                `protobuf:"bytes,2,req,name=cname" json:"cname,omitempty"`
	Sname            *string                `protobuf:"bytes,3,req,name=sname" json:"sname,omitempty"`
	Status           *StatusResponse_Status `protobuf:"varint,4,req,name=status,enum=message.StatusResponse_Status" json:"status,omitempty"`
	BindAddr         *string                `protobuf:"bytes,5,req,name=bindAddr" json:"bindAddr,omitempty"`
	BindPort         *int32                 `protobuf:"varint,6,req,name=bindPort" json:"bindPort,omitempty"`
	Err              *string                `protobuf:"bytes,7,req,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *StatusResponse_Data) Reset()                    { *m = StatusResponse_Data{} }
func (m *StatusResponse_Data) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse_Data) ProtoMessage()               {}
func (*StatusResponse_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

func (m *StatusResponse_Data) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StatusResponse_Data) GetCname() string {
	if m != nil && m.Cname != nil {
		return *m.Cname
	}
	return ""
}

func (m *StatusResponse_Data) GetSname() string {
	if m != nil && m.Sname != nil {
		return *m.Sname
	}
	return ""
}

func (m *StatusResponse_Data) GetStatus() StatusResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StatusResponse_STOPPED
}

func (m *StatusResponse_Data) GetBindAddr() string {
	if m != nil && m.BindAddr != nil {
		return *m.BindAddr
	}
	return ""
}

func (m *StatusResponse_Data) GetBindPort() int32 {
	if m != nil && m.BindPort != nil {
		return *m.BindPort
	}
	return 0
}

func (m *StatusResponse_Data) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

// start 命令的返回结果
type StartResponse struct {
	Data             []*StartResponse_Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *StartResponse) Reset()                    { *m = StartResponse{} }
func (m *StartResponse) String() string            { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()               {}
func (*StartResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *StartResponse) GetData() []*StartResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StartResponse_Data struct {
	Name             *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Status           *StartResponse_Status `protobuf:"varint,2,req,name=status,enum=message.StartResponse_Status" json:"status,omitempty"`
	Err              *string               `protobuf:"bytes,3,req,name=err" json:"err,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *StartResponse_Data) Reset()                    { *m = StartResponse_Data{} }
func (m *StartResponse_Data) String() string            { return proto.CompactTextString(m) }
func (*StartResponse_Data) ProtoMessage()               {}
func (*StartResponse_Data) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2, 0} }

func (m *StartResponse_Data) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StartResponse_Data) GetStatus() StartResponse_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return StartResponse_STARTED
}

func (m *StartResponse_Data) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

type Response struct {
	Err              *Error          `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Type             *RequestType    `protobuf:"varint,2,req,name=type,enum=message.RequestType" json:"type,omitempty"`
	Status           *StatusResponse `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Start            *StartResponse  `protobuf:"bytes,4,opt,name=start" json:"start,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *Response) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_STATUS
}

func (m *Response) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Response) GetStart() *StartResponse {
	if m != nil {
		return m.Start
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "message.Error")
	proto.RegisterType((*StatusResponse)(nil), "message.StatusResponse")
	proto.RegisterType((*StatusResponse_Data)(nil), "message.StatusResponse.Data")
	proto.RegisterType((*StartResponse)(nil), "message.StartResponse")
	proto.RegisterType((*StartResponse_Data)(nil), "message.StartResponse.Data")
	proto.RegisterType((*Response)(nil), "message.Response")
	proto.RegisterEnum("message.StatusResponse_Status", StatusResponse_Status_name, StatusResponse_Status_value)
	proto.RegisterEnum("message.StartResponse_Status", StartResponse_Status_name, StartResponse_Status_value)
}

func init() { proto.RegisterFile("src/skywalker/message/response.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xdf, 0x4e, 0xfa, 0x30,
	0x18, 0xcd, 0xd6, 0x8d, 0x3f, 0x1f, 0x3f, 0xc8, 0xd2, 0x90, 0x9f, 0x0b, 0xa8, 0x21, 0x53, 0x23,
	0x9a, 0x30, 0x12, 0xde, 0x80, 0x04, 0x62, 0xbc, 0x81, 0xa5, 0xe0, 0x03, 0x4c, 0xd6, 0x10, 0x83,
	0x30, 0x6c, 0x4b, 0x0c, 0x97, 0x3e, 0x83, 0x97, 0x3e, 0x8a, 0x2f, 0x67, 0xd7, 0xce, 0x0a, 0x09,
	0xbb, 0xdb, 0xf9, 0x7a, 0x76, 0x7a, 0xce, 0xf9, 0x0a, 0xd7, 0x9c, 0x2d, 0xfa, 0x7c, 0xb5, 0x7f,
	0x8f, 0x5f, 0x57, 0x94, 0xf5, 0xd7, 0x94, 0xf3, 0x78, 0x49, 0xfb, 0x8c, 0xf2, 0x6d, 0xba, 0xe1,
	0x34, 0xdc, 0xb2, 0x54, 0xa4, 0xb8, 0x9c, 0xcf, 0x5b, 0x57, 0x45, 0xf4, 0xb7, 0x1d, 0xe5, 0x42,
	0xb3, 0x83, 0x26, 0xb8, 0x63, 0xc6, 0x52, 0x86, 0x6b, 0x80, 0xd6, 0x7c, 0xe9, 0x5b, 0x1d, 0xbb,
	0x5b, 0x0d, 0x3e, 0x6c, 0x68, 0xcc, 0x44, 0x2c, 0x76, 0x9c, 0xe4, 0xe2, 0xf8, 0x1e, 0x9c, 0x24,
	0x16, 0xb1, 0x24, 0xa0, 0x6e, 0x6d, 0x70, 0x1e, 0xe6, 0x72, 0xe1, 0x31, 0x2d, 0x1c, 0x49, 0x4e,
	0xeb, 0xd3, 0x02, 0x27, 0xfb, 0xc0, 0xff, 0xc0, 0xd9, 0xc4, 0x6b, 0xaa, 0x55, 0x71, 0x1d, 0xdc,
	0x85, 0x82, 0xf6, 0x2f, 0xe4, 0x0a, 0x22, 0x05, 0x43, 0x28, 0x71, 0xa5, 0xe5, 0x3b, 0x12, 0x37,
	0x06, 0x97, 0x45, 0x57, 0x68, 0x88, 0x3d, 0xa8, 0x3c, 0xbf, 0x6c, 0x92, 0x61, 0x92, 0x30, 0xdf,
	0x55, 0x0a, 0xf9, 0x24, 0x4a, 0x99, 0xf0, 0x4b, 0x72, 0xe2, 0x66, 0xa1, 0x28, 0x63, 0x7e, 0x59,
	0x85, 0xea, 0x41, 0x29, 0xff, 0xb5, 0x06, 0xe5, 0xd9, 0x7c, 0x1a, 0x45, 0xe3, 0x91, 0x67, 0x65,
	0x80, 0x3c, 0x4d, 0x26, 0x8f, 0x93, 0x07, 0xcf, 0xc6, 0x55, 0x59, 0x07, 0x21, 0x53, 0xe2, 0xa1,
	0xe0, 0xdb, 0x82, 0xba, 0xe4, 0x33, 0x61, 0x2a, 0xb8, 0x3b, 0xaa, 0xa0, 0x7d, 0xe8, 0xef, 0x8f,
	0xa5, 0x1b, 0x88, 0x4e, 0x16, 0xd0, 0x33, 0x11, 0x6d, 0x15, 0xf1, 0xa2, 0x40, 0xc2, 0xd8, 0x54,
	0xee, 0xd1, 0x29, 0xf7, 0x43, 0x32, 0x57, 0xee, 0x8d, 0x61, 0xfb, 0x30, 0x08, 0x0a, 0xbe, 0x2c,
	0xa8, 0x18, 0xe3, 0x6d, 0x2d, 0x64, 0x75, 0x2c, 0xe9, 0xbb, 0x61, 0x2e, 0xd5, 0x8b, 0x0f, 0xc0,
	0x11, 0xfb, 0x2d, 0xcd, 0x2d, 0x35, 0xcd, 0x29, 0xd1, 0xef, 0x64, 0x2e, 0xcf, 0xf0, 0xad, 0x31,
	0x8e, 0x94, 0xc6, 0x59, 0xc1, 0x6e, 0xf0, 0x8d, 0xdc, 0x69, 0x16, 0x45, 0xee, 0x30, 0xe3, 0xfd,
	0x3f, 0x1d, 0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x83, 0xf0, 0x68, 0xba, 0xca, 0x02, 0x00, 0x00,
}
