// Code generated by protoc-gen-go.
// source: src/skywalker/message/response.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 出错
type Error struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Error) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type StatusResponse struct {
	Status           []*StatusResponse_Status `protobuf:"bytes,1,rep,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *StatusResponse) GetStatus() []*StatusResponse_Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type StatusResponse_Status struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Cname            *string `protobuf:"bytes,2,req,name=cname" json:"cname,omitempty"`
	Sname            *string `protobuf:"bytes,3,req,name=sname" json:"sname,omitempty"`
	Running          *bool   `protobuf:"varint,4,req,name=running" json:"running,omitempty"`
	BindAddr         *string `protobuf:"bytes,5,req,name=bindAddr" json:"bindAddr,omitempty"`
	BindPort         *int32  `protobuf:"varint,6,req,name=bindPort" json:"bindPort,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusResponse_Status) Reset()                    { *m = StatusResponse_Status{} }
func (m *StatusResponse_Status) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse_Status) ProtoMessage()               {}
func (*StatusResponse_Status) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

func (m *StatusResponse_Status) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StatusResponse_Status) GetCname() string {
	if m != nil && m.Cname != nil {
		return *m.Cname
	}
	return ""
}

func (m *StatusResponse_Status) GetSname() string {
	if m != nil && m.Sname != nil {
		return *m.Sname
	}
	return ""
}

func (m *StatusResponse_Status) GetRunning() bool {
	if m != nil && m.Running != nil {
		return *m.Running
	}
	return false
}

func (m *StatusResponse_Status) GetBindAddr() string {
	if m != nil && m.BindAddr != nil {
		return *m.BindAddr
	}
	return ""
}

func (m *StatusResponse_Status) GetBindPort() int32 {
	if m != nil && m.BindPort != nil {
		return *m.BindPort
	}
	return 0
}

type Response struct {
	Err              *Error          `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Type             *RequestType    `protobuf:"varint,2,req,name=type,enum=message.RequestType" json:"type,omitempty"`
	Status           *StatusResponse `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *Response) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_STATUS
}

func (m *Response) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "message.Error")
	proto.RegisterType((*StatusResponse)(nil), "message.StatusResponse")
	proto.RegisterType((*StatusResponse_Status)(nil), "message.StatusResponse.Status")
	proto.RegisterType((*Response)(nil), "message.Response")
}

func init() { proto.RegisterFile("src/skywalker/message/response.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xe9, 0xd2, 0x76, 0xf5, 0x4c, 0xab, 0x84, 0x81, 0x65, 0x82, 0x48, 0x15, 0xdc, 0x55,
	0x0b, 0x7b, 0x03, 0x2f, 0xbc, 0x97, 0xe9, 0x0b, 0xd4, 0x35, 0x94, 0x32, 0x9b, 0xd4, 0x73, 0x52,
	0x64, 0xcf, 0xe4, 0x4b, 0x1a, 0x92, 0x18, 0xd8, 0x45, 0xef, 0xf2, 0xff, 0xe7, 0xe3, 0x3f, 0xe7,
	0x0f, 0x3c, 0x11, 0x1e, 0x6a, 0x3a, 0x9e, 0x7e, 0x9a, 0xaf, 0xa3, 0xc0, 0x7a, 0x10, 0x44, 0x4d,
	0x27, 0x6a, 0x14, 0x34, 0x2a, 0x49, 0xa2, 0x1a, 0x51, 0x69, 0xc5, 0x97, 0xde, 0xdf, 0x3c, 0xce,
	0xe1, 0xdf, 0x93, 0x20, 0xed, 0xe8, 0x72, 0x0d, 0xc9, 0x2b, 0xa2, 0x42, 0xbe, 0x02, 0x36, 0x50,
	0x57, 0x44, 0x0f, 0x8b, 0xed, 0x45, 0xf9, 0x1b, 0x41, 0xfe, 0xae, 0x1b, 0x3d, 0xd1, 0xde, 0x87,
	0xf3, 0x0a, 0x52, 0xb2, 0x8e, 0x41, 0xd8, 0x76, 0xb5, 0xbb, 0xaf, 0x7c, 0x60, 0x75, 0x0e, 0x7a,
	0xb9, 0xe9, 0x21, 0x75, 0x2f, 0x7e, 0x09, 0xb1, 0x6c, 0x06, 0xe1, 0xa2, 0xf9, 0x15, 0x24, 0x07,
	0x2b, 0x17, 0xff, 0x92, 0xac, 0x64, 0x56, 0x5e, 0xc3, 0x12, 0x27, 0x29, 0x7b, 0xd9, 0x15, 0xb1,
	0x31, 0x32, 0x7e, 0x03, 0xd9, 0x67, 0x2f, 0xdb, 0x97, 0xb6, 0xc5, 0x22, 0xb1, 0x88, 0x77, 0xde,
	0x14, 0xea, 0x22, 0x35, 0x4e, 0x52, 0x6a, 0xc8, 0xc2, 0x99, 0x77, 0xc0, 0x04, 0xa2, 0xd9, 0x15,
	0x99, 0x1b, 0xf3, 0x70, 0xa3, 0xeb, 0x58, 0x42, 0xac, 0x4f, 0xa3, 0x5b, 0x9d, 0xef, 0xd6, 0x61,
	0xba, 0x77, 0x5f, 0xf2, 0x61, 0x66, 0xfc, 0x39, 0xf4, 0x64, 0x36, 0xe3, 0x76, 0xa6, 0xe7, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xb4, 0xe8, 0xf5, 0x8e, 0x01, 0x00, 0x00,
}
