// Code generated by protoc-gen-go.
// source: src/skywalker/message/response.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RelayStatus struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Cname            *string `protobuf:"bytes,2,req,name=cname" json:"cname,omitempty"`
	Sname            *string `protobuf:"bytes,3,req,name=sname" json:"sname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RelayStatus) Reset()                    { *m = RelayStatus{} }
func (m *RelayStatus) String() string            { return proto.CompactTextString(m) }
func (*RelayStatus) ProtoMessage()               {}
func (*RelayStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RelayStatus) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *RelayStatus) GetCname() string {
	if m != nil && m.Cname != nil {
		return *m.Cname
	}
	return ""
}

func (m *RelayStatus) GetSname() string {
	if m != nil && m.Sname != nil {
		return *m.Sname
	}
	return ""
}

type Response struct {
	Type             *RequestType   `protobuf:"varint,1,req,name=type,enum=message.RequestType" json:"type,omitempty"`
	Status           []*RelayStatus `protobuf:"bytes,2,rep,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Response) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_STATUS
}

func (m *Response) GetStatus() []*RelayStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*RelayStatus)(nil), "message.RelayStatus")
	proto.RegisterType((*Response)(nil), "message.Response")
}

func init() { proto.RegisterFile("src/skywalker/message/response.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x52, 0x29, 0x2e, 0x4a, 0xd6,
	0x2f, 0xce, 0xae, 0x2c, 0x4f, 0xcc, 0xc9, 0x4e, 0x2d, 0xd2, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0xd5, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x87, 0x8a, 0x4b, 0x29, 0xe3, 0x52, 0x5e, 0x58, 0x9a, 0x5a, 0x5c, 0x02, 0x51, 0xad,
	0x64, 0xc9, 0xc5, 0x1d, 0x94, 0x9a, 0x93, 0x58, 0x19, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c, 0xc4,
	0xc3, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x29, 0xc4, 0xcb, 0xc5,
	0x9a, 0x0c, 0xe6, 0x32, 0xc1, 0xb8, 0xc5, 0x60, 0x2e, 0x33, 0x88, 0xab, 0x14, 0xc2, 0xc5, 0x11,
	0x04, 0xb5, 0x5a, 0x48, 0x89, 0x8b, 0xa5, 0xa4, 0xb2, 0x00, 0xa2, 0x8f, 0xcf, 0x48, 0x44, 0x0f,
	0x6a, 0x99, 0x5e, 0x10, 0xc4, 0xb2, 0x10, 0xa0, 0x9c, 0x90, 0x0a, 0x17, 0x5b, 0x31, 0xd8, 0x16,
	0xa0, 0x71, 0xcc, 0x1a, 0xdc, 0x28, 0xaa, 0xe0, 0x2e, 0x00, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc4,
	0x3f, 0xcf, 0xe9, 0xe5, 0x00, 0x00, 0x00,
}
