// Code generated by protoc-gen-go.
// source: src/skywalker/rpc/request.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	src/skywalker/rpc/request.proto
	src/skywalker/rpc/response.proto

It has these top-level messages:
	CommonRequest
	AuthRequest
	Request
	Error
	AuthResponse
	StatusResponse
	StartResponse
	StopResponse
	InfoResponse
	ReloadResponse
	Response
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_AUTH    RequestType = 1
	RequestType_STATUS  RequestType = 2
	RequestType_START   RequestType = 3
	RequestType_STOP    RequestType = 4
	RequestType_RESTART RequestType = 5
	RequestType_INFO    RequestType = 6
	RequestType_RELOAD  RequestType = 7
)

var RequestType_name = map[int32]string{
	1: "AUTH",
	2: "STATUS",
	3: "START",
	4: "STOP",
	5: "RESTART",
	6: "INFO",
	7: "RELOAD",
}
var RequestType_value = map[string]int32{
	"AUTH":    1,
	"STATUS":  2,
	"START":   3,
	"STOP":    4,
	"RESTART": 5,
	"INFO":    6,
	"RELOAD":  7,
}

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}
func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (x *RequestType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RequestType_value, data, "RequestType")
	if err != nil {
		return err
	}
	*x = RequestType(value)
	return nil
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CommonRequest struct {
	Name             []string `protobuf:"bytes,1,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CommonRequest) Reset()                    { *m = CommonRequest{} }
func (m *CommonRequest) String() string            { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()               {}
func (*CommonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type AuthRequest struct {
	Username         *string `protobuf:"bytes,1,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,2,req,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

type Request struct {
	Version          *int32         `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Type             *RequestType   `protobuf:"varint,2,req,name=type,enum=rpc.RequestType" json:"type,omitempty"`
	Common           *CommonRequest `protobuf:"bytes,3,opt,name=common" json:"common,omitempty"`
	Auth             *AuthRequest   `protobuf:"bytes,4,opt,name=auth" json:"auth,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Request) GetType() RequestType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RequestType_AUTH
}

func (m *Request) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Request) GetAuth() *AuthRequest {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonRequest)(nil), "rpc.CommonRequest")
	proto.RegisterType((*AuthRequest)(nil), "rpc.AuthRequest")
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterEnum("rpc.RequestType", RequestType_name, RequestType_value)
}

func init() { proto.RegisterFile("src/skywalker/rpc/request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xce, 0xc1, 0x4e, 0xb3, 0x40,
	0x14, 0x05, 0xe0, 0x00, 0x03, 0x94, 0xcb, 0xff, 0xeb, 0x64, 0x56, 0x6c, 0xac, 0x0d, 0x2b, 0xe2,
	0x02, 0x62, 0xdf, 0x80, 0x68, 0x8d, 0x26, 0x46, 0x0c, 0x4c, 0x57, 0xae, 0x08, 0x4e, 0x52, 0x53,
	0x61, 0xc6, 0x3b, 0x60, 0xc3, 0xc6, 0x67, 0x37, 0x0c, 0x6d, 0x52, 0xb7, 0xe7, 0x7e, 0xf7, 0xe4,
	0xc0, 0xb5, 0xc6, 0x26, 0xd3, 0xfb, 0xf1, 0x50, 0x7f, 0xee, 0x05, 0x66, 0xa8, 0x9a, 0x0c, 0xc5,
	0xd7, 0x20, 0x74, 0x9f, 0x2a, 0x94, 0xbd, 0x64, 0x0e, 0xaa, 0x26, 0xbe, 0x82, 0xff, 0x77, 0xb2,
	0x6d, 0x65, 0x57, 0xce, 0x37, 0xf6, 0x0f, 0x48, 0x57, 0xb7, 0x22, 0xb2, 0x56, 0x4e, 0x12, 0xc4,
	0xb7, 0x10, 0xe6, 0x43, 0xbf, 0x3b, 0x1d, 0x29, 0x2c, 0x06, 0x2d, 0xf0, 0x08, 0xec, 0x24, 0x98,
	0x12, 0x55, 0x6b, 0x7d, 0x90, 0xf8, 0x1e, 0xd9, 0x53, 0x12, 0xff, 0x80, 0x7f, 0xe2, 0x97, 0xe0,
	0x7f, 0x0b, 0xd4, 0x1f, 0xb2, 0x33, 0xda, 0x65, 0x4b, 0x20, 0xfd, 0xa8, 0x84, 0x91, 0x17, 0x6b,
	0x9a, 0xa2, 0x6a, 0xd2, 0x23, 0xe6, 0xa3, 0x12, 0x2c, 0x06, 0xaf, 0x31, 0x6b, 0x22, 0x67, 0x65,
	0x25, 0xe1, 0x9a, 0x19, 0xf1, 0x77, 0xe0, 0x12, 0x48, 0x3d, 0xf4, 0xbb, 0x88, 0x18, 0x31, 0x77,
	0x9c, 0x6d, 0xbc, 0x79, 0x83, 0xf0, 0xbc, 0x72, 0x01, 0x24, 0xdf, 0xf2, 0x47, 0x6a, 0x31, 0x00,
	0xaf, 0xe2, 0x39, 0xdf, 0x56, 0xd4, 0x66, 0x01, 0xb8, 0x15, 0xcf, 0x4b, 0x4e, 0x9d, 0x09, 0x54,
	0xbc, 0x78, 0xa5, 0x84, 0x85, 0xe0, 0x97, 0x9b, 0x39, 0x76, 0xa7, 0xf8, 0xe9, 0xe5, 0xa1, 0xa0,
	0xde, 0xf4, 0x57, 0x6e, 0x9e, 0x8b, 0xfc, 0x9e, 0xfa, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x82,
	0x0a, 0xb7, 0x9b, 0x55, 0x01, 0x00, 0x00,
}
