// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/skywalker/rpc/request.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_AUTH       RequestType = 0
	RequestType_STATUS     RequestType = 1
	RequestType_START      RequestType = 2
	RequestType_STOP       RequestType = 3
	RequestType_RESTART    RequestType = 4
	RequestType_INFO       RequestType = 5
	RequestType_RELOAD     RequestType = 6
	RequestType_QUIT       RequestType = 7
	RequestType_CLEARCACHE RequestType = 8
	RequestType_LIST       RequestType = 9
)

var RequestType_name = map[int32]string{
	0: "AUTH",
	1: "STATUS",
	2: "START",
	3: "STOP",
	4: "RESTART",
	5: "INFO",
	6: "RELOAD",
	7: "QUIT",
	8: "CLEARCACHE",
	9: "LIST",
}
var RequestType_value = map[string]int32{
	"AUTH":       0,
	"STATUS":     1,
	"START":      2,
	"STOP":       3,
	"RESTART":    4,
	"INFO":       5,
	"RELOAD":     6,
	"QUIT":       7,
	"CLEARCACHE": 8,
	"LIST":       9,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_request_cecd5ca6f3fa4b99, []int{0}
}

type CommonRequest struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonRequest) Reset()         { *m = CommonRequest{} }
func (m *CommonRequest) String() string { return proto.CompactTextString(m) }
func (*CommonRequest) ProtoMessage()    {}
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_cecd5ca6f3fa4b99, []int{0}
}
func (m *CommonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonRequest.Unmarshal(m, b)
}
func (m *CommonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonRequest.Marshal(b, m, deterministic)
}
func (dst *CommonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonRequest.Merge(dst, src)
}
func (m *CommonRequest) XXX_Size() int {
	return xxx_messageInfo_CommonRequest.Size(m)
}
func (m *CommonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommonRequest proto.InternalMessageInfo

func (m *CommonRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type AuthRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_cecd5ca6f3fa4b99, []int{1}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	Version              int32          `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Type                 RequestType    `protobuf:"varint,2,opt,name=type,proto3,enum=rpc.RequestType" json:"type,omitempty"`
	Common               *CommonRequest `protobuf:"bytes,3,opt,name=common,proto3" json:"common,omitempty"`
	Auth                 *AuthRequest   `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_cecd5ca6f3fa4b99, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Request) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_AUTH
}

func (m *Request) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *Request) GetAuth() *AuthRequest {
	if m != nil {
		return m.Auth
	}
	return nil
}

func init() {
	proto.RegisterType((*CommonRequest)(nil), "rpc.CommonRequest")
	proto.RegisterType((*AuthRequest)(nil), "rpc.AuthRequest")
	proto.RegisterType((*Request)(nil), "rpc.Request")
	proto.RegisterEnum("rpc.RequestType", RequestType_name, RequestType_value)
}

func init() {
	proto.RegisterFile("src/skywalker/rpc/request.proto", fileDescriptor_request_cecd5ca6f3fa4b99)
}

var fileDescriptor_request_cecd5ca6f3fa4b99 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xd1, 0x4e, 0xf2, 0x30,
	0x14, 0xc7, 0xbf, 0xb1, 0xb1, 0xb1, 0xb3, 0x7c, 0xa4, 0xe9, 0xd5, 0xe2, 0x8d, 0x04, 0xbd, 0x20,
	0x5c, 0x40, 0x82, 0x4f, 0xd0, 0xcc, 0x19, 0x48, 0x88, 0x68, 0x57, 0x1e, 0x60, 0xce, 0x26, 0x18,
	0x64, 0xad, 0xed, 0x26, 0xd9, 0x95, 0x0f, 0xe2, 0xcb, 0x9a, 0x76, 0x9b, 0xc1, 0xbb, 0x9e, 0xf3,
	0xfb, 0x9d, 0x7f, 0x7b, 0x52, 0xb8, 0xd6, 0xaa, 0x58, 0xea, 0x63, 0x73, 0xce, 0xdf, 0x8f, 0x5c,
	0x2d, 0x95, 0x2c, 0x96, 0x8a, 0x7f, 0xd4, 0x5c, 0x57, 0x0b, 0xa9, 0x44, 0x25, 0xb0, 0xab, 0x64,
	0x31, 0xbd, 0x81, 0xff, 0x89, 0x38, 0x9d, 0x44, 0x49, 0x5b, 0x86, 0x31, 0x78, 0x65, 0x7e, 0xe2,
	0xb1, 0x33, 0x71, 0x67, 0x21, 0xb5, 0xe7, 0x69, 0x0a, 0x11, 0xa9, 0xab, 0x43, 0xaf, 0x5c, 0xc1,
	0xa8, 0xd6, 0x5c, 0x75, 0x9a, 0x33, 0x0b, 0xe9, 0x6f, 0x6d, 0x98, 0xcc, 0xb5, 0x3e, 0x0b, 0xf5,
	0x1a, 0x0f, 0x5a, 0xd6, 0xd7, 0xd3, 0x6f, 0x07, 0x82, 0x3e, 0x23, 0x86, 0xe0, 0x93, 0x2b, 0xfd,
	0x26, 0x4a, 0x1b, 0x31, 0xa4, 0x7d, 0x89, 0x6f, 0xc1, 0xab, 0x1a, 0xc9, 0xed, 0xf4, 0x78, 0x85,
	0x16, 0x4a, 0x16, 0x8b, 0x6e, 0x8a, 0x35, 0x92, 0x53, 0x4b, 0xf1, 0x1c, 0xfc, 0xc2, 0xbe, 0x3b,
	0x76, 0x27, 0xce, 0x2c, 0x5a, 0x61, 0xeb, 0xfd, 0x59, 0x85, 0x76, 0x86, 0x49, 0xcc, 0xeb, 0xea,
	0x10, 0x7b, 0xd6, 0x6c, 0x13, 0x2f, 0xf6, 0xa1, 0x96, 0xce, 0xbf, 0x20, 0xba, 0xb8, 0x06, 0x8f,
	0xc0, 0x23, 0x7b, 0xb6, 0x46, 0xff, 0x30, 0x80, 0x9f, 0x31, 0xc2, 0xf6, 0x19, 0x72, 0x70, 0x08,
	0xc3, 0x8c, 0x11, 0xca, 0xd0, 0xc0, 0x08, 0x19, 0xdb, 0x3d, 0x21, 0x17, 0x47, 0x10, 0xd0, 0xb4,
	0x6d, 0x7b, 0xa6, 0xbd, 0x79, 0x7c, 0xd8, 0xa1, 0xa1, 0x99, 0xa3, 0xe9, 0x76, 0x47, 0xee, 0x91,
	0x6f, 0xba, 0xcf, 0xfb, 0x0d, 0x43, 0x01, 0x1e, 0x03, 0x24, 0xdb, 0x94, 0xd0, 0x84, 0x24, 0xeb,
	0x14, 0x8d, 0x0c, 0xd9, 0x6e, 0x32, 0x86, 0xc2, 0x17, 0xdf, 0x7e, 0xcb, 0xdd, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x71, 0x0f, 0x94, 0x7a, 0xb9, 0x01, 0x00, 0x00,
}
