// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/skywalker/rpc/response.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthResponse_Status int32

const (
	AuthResponse_SUCCESS AuthResponse_Status = 0
	AuthResponse_FAILURE AuthResponse_Status = 1
)

var AuthResponse_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}
var AuthResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x AuthResponse_Status) String() string {
	return proto.EnumName(AuthResponse_Status_name, int32(x))
}
func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{1, 0}
}

type StatusResponse_Status int32

const (
	StatusResponse_STOPPED StatusResponse_Status = 0
	StatusResponse_RUNNING StatusResponse_Status = 1
	StatusResponse_ERROR   StatusResponse_Status = 2
)

var StatusResponse_Status_name = map[int32]string{
	0: "STOPPED",
	1: "RUNNING",
	2: "ERROR",
}
var StatusResponse_Status_value = map[string]int32{
	"STOPPED": 0,
	"RUNNING": 1,
	"ERROR":   2,
}

func (x StatusResponse_Status) String() string {
	return proto.EnumName(StatusResponse_Status_name, int32(x))
}
func (StatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{2, 0}
}

type StartResponse_Status int32

const (
	StartResponse_STARTED StartResponse_Status = 0
	StartResponse_ERROR   StartResponse_Status = 1
	StartResponse_RUNNING StartResponse_Status = 2
)

var StartResponse_Status_name = map[int32]string{
	0: "STARTED",
	1: "ERROR",
	2: "RUNNING",
}
var StartResponse_Status_value = map[string]int32{
	"STARTED": 0,
	"ERROR":   1,
	"RUNNING": 2,
}

func (x StartResponse_Status) String() string {
	return proto.EnumName(StartResponse_Status_name, int32(x))
}
func (StartResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{3, 0}
}

type StopResponse_Status int32

const (
	StopResponse_STOPPED   StopResponse_Status = 0
	StopResponse_ERROR     StopResponse_Status = 1
	StopResponse_UNRUNNING StopResponse_Status = 2
)

var StopResponse_Status_name = map[int32]string{
	0: "STOPPED",
	1: "ERROR",
	2: "UNRUNNING",
}
var StopResponse_Status_value = map[string]int32{
	"STOPPED":   0,
	"ERROR":     1,
	"UNRUNNING": 2,
}

func (x StopResponse_Status) String() string {
	return proto.EnumName(StopResponse_Status_name, int32(x))
}
func (StopResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{4, 0}
}

type InfoResponse_Status int32

const (
	InfoResponse_STOPPED InfoResponse_Status = 0
	InfoResponse_RUNNING InfoResponse_Status = 1
	InfoResponse_ERROR   InfoResponse_Status = 2
)

var InfoResponse_Status_name = map[int32]string{
	0: "STOPPED",
	1: "RUNNING",
	2: "ERROR",
}
var InfoResponse_Status_value = map[string]int32{
	"STOPPED": 0,
	"RUNNING": 1,
	"ERROR":   2,
}

func (x InfoResponse_Status) String() string {
	return proto.EnumName(InfoResponse_Status_name, int32(x))
}
func (InfoResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{5, 0}
}

type QuitResponse_Status int32

const (
	QuitResponse_QUITED QuitResponse_Status = 0
	QuitResponse_ERROR  QuitResponse_Status = 1
)

var QuitResponse_Status_name = map[int32]string{
	0: "QUITED",
	1: "ERROR",
}
var QuitResponse_Status_value = map[string]int32{
	"QUITED": 0,
	"ERROR":  1,
}

func (x QuitResponse_Status) String() string {
	return proto.EnumName(QuitResponse_Status_name, int32(x))
}
func (QuitResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{7, 0}
}

type ClearCacheResponse_Status int32

const (
	ClearCacheResponse_SUCCESS ClearCacheResponse_Status = 0
)

var ClearCacheResponse_Status_name = map[int32]string{
	0: "SUCCESS",
}
var ClearCacheResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
}

func (x ClearCacheResponse_Status) String() string {
	return proto.EnumName(ClearCacheResponse_Status_name, int32(x))
}
func (ClearCacheResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{8, 0}
}

type ListResponse_Status int32

const (
	ListResponse_SUCCESS ListResponse_Status = 0
)

var ListResponse_Status_name = map[int32]string{
	0: "SUCCESS",
}
var ListResponse_Status_value = map[string]int32{
	"SUCCESS": 0,
}

func (x ListResponse_Status) String() string {
	return proto.EnumName(ListResponse_Status_name, int32(x))
}
func (ListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{9, 0}
}

// 出错
type Error struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type AuthResponse struct {
	Status               AuthResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.AuthResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetStatus() AuthResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthResponse_SUCCESS
}

// status 命令的返回结果
type StatusResponse struct {
	Data                 []*StatusResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{2}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetData() []*StatusResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StatusResponse_Data struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cname                string                `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	Sname                string                `protobuf:"bytes,3,opt,name=sname,proto3" json:"sname,omitempty"`
	Status               StatusResponse_Status `protobuf:"varint,4,opt,name=status,proto3,enum=rpc.StatusResponse_Status" json:"status,omitempty"`
	BindAddr             string                `protobuf:"bytes,5,opt,name=bindAddr,proto3" json:"bindAddr,omitempty"`
	BindPort             int32                 `protobuf:"varint,6,opt,name=bindPort,proto3" json:"bindPort,omitempty"`
	StartTime            int64                 `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Err                  string                `protobuf:"bytes,8,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StatusResponse_Data) Reset()         { *m = StatusResponse_Data{} }
func (m *StatusResponse_Data) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_Data) ProtoMessage()    {}
func (*StatusResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{2, 0}
}
func (m *StatusResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Data.Unmarshal(m, b)
}
func (m *StatusResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Data.Marshal(b, m, deterministic)
}
func (dst *StatusResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Data.Merge(dst, src)
}
func (m *StatusResponse_Data) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Data.Size(m)
}
func (m *StatusResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Data proto.InternalMessageInfo

func (m *StatusResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatusResponse_Data) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *StatusResponse_Data) GetSname() string {
	if m != nil {
		return m.Sname
	}
	return ""
}

func (m *StatusResponse_Data) GetStatus() StatusResponse_Status {
	if m != nil {
		return m.Status
	}
	return StatusResponse_STOPPED
}

func (m *StatusResponse_Data) GetBindAddr() string {
	if m != nil {
		return m.BindAddr
	}
	return ""
}

func (m *StatusResponse_Data) GetBindPort() int32 {
	if m != nil {
		return m.BindPort
	}
	return 0
}

func (m *StatusResponse_Data) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *StatusResponse_Data) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// start 命令的返回结果
type StartResponse struct {
	Data                 []*StartResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StartResponse) Reset()         { *m = StartResponse{} }
func (m *StartResponse) String() string { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()    {}
func (*StartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{3}
}
func (m *StartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse.Unmarshal(m, b)
}
func (m *StartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse.Marshal(b, m, deterministic)
}
func (dst *StartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse.Merge(dst, src)
}
func (m *StartResponse) XXX_Size() int {
	return xxx_messageInfo_StartResponse.Size(m)
}
func (m *StartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse proto.InternalMessageInfo

func (m *StartResponse) GetData() []*StartResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StartResponse_Data struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               StartResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=rpc.StartResponse_Status" json:"status,omitempty"`
	Err                  string               `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StartResponse_Data) Reset()         { *m = StartResponse_Data{} }
func (m *StartResponse_Data) String() string { return proto.CompactTextString(m) }
func (*StartResponse_Data) ProtoMessage()    {}
func (*StartResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{3, 0}
}
func (m *StartResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResponse_Data.Unmarshal(m, b)
}
func (m *StartResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResponse_Data.Marshal(b, m, deterministic)
}
func (dst *StartResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResponse_Data.Merge(dst, src)
}
func (m *StartResponse_Data) XXX_Size() int {
	return xxx_messageInfo_StartResponse_Data.Size(m)
}
func (m *StartResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_StartResponse_Data proto.InternalMessageInfo

func (m *StartResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartResponse_Data) GetStatus() StartResponse_Status {
	if m != nil {
		return m.Status
	}
	return StartResponse_STARTED
}

func (m *StartResponse_Data) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type StopResponse struct {
	Data                 []*StopResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{4}
}
func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (dst *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(dst, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetData() []*StopResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type StopResponse_Data struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               StopResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=rpc.StopResponse_Status" json:"status,omitempty"`
	Err                  string              `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StopResponse_Data) Reset()         { *m = StopResponse_Data{} }
func (m *StopResponse_Data) String() string { return proto.CompactTextString(m) }
func (*StopResponse_Data) ProtoMessage()    {}
func (*StopResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{4, 0}
}
func (m *StopResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse_Data.Unmarshal(m, b)
}
func (m *StopResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse_Data.Marshal(b, m, deterministic)
}
func (dst *StopResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse_Data.Merge(dst, src)
}
func (m *StopResponse_Data) XXX_Size() int {
	return xxx_messageInfo_StopResponse_Data.Size(m)
}
func (m *StopResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse_Data proto.InternalMessageInfo

func (m *StopResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StopResponse_Data) GetStatus() StopResponse_Status {
	if m != nil {
		return m.Status
	}
	return StopResponse_STOPPED
}

func (m *StopResponse_Data) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type InfoResponse struct {
	Data                 []*InfoResponse_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{5}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetData() []*InfoResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type InfoResponse_Info struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse_Info) Reset()         { *m = InfoResponse_Info{} }
func (m *InfoResponse_Info) String() string { return proto.CompactTextString(m) }
func (*InfoResponse_Info) ProtoMessage()    {}
func (*InfoResponse_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{5, 0}
}
func (m *InfoResponse_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse_Info.Unmarshal(m, b)
}
func (m *InfoResponse_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse_Info.Marshal(b, m, deterministic)
}
func (dst *InfoResponse_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse_Info.Merge(dst, src)
}
func (m *InfoResponse_Info) XXX_Size() int {
	return xxx_messageInfo_InfoResponse_Info.Size(m)
}
func (m *InfoResponse_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse_Info.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse_Info proto.InternalMessageInfo

func (m *InfoResponse_Info) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InfoResponse_Info) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type InfoResponse_Data struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cname                string               `protobuf:"bytes,2,opt,name=cname,proto3" json:"cname,omitempty"`
	Sname                string               `protobuf:"bytes,3,opt,name=sname,proto3" json:"sname,omitempty"`
	Status               InfoResponse_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=rpc.InfoResponse_Status" json:"status,omitempty"`
	BindAddr             string               `protobuf:"bytes,5,opt,name=bindAddr,proto3" json:"bindAddr,omitempty"`
	BindPort             int32                `protobuf:"varint,6,opt,name=bindPort,proto3" json:"bindPort,omitempty"`
	StartTime            int64                `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	Sent                 int64                `protobuf:"varint,8,opt,name=sent,proto3" json:"sent,omitempty"`
	Received             int64                `protobuf:"varint,9,opt,name=received,proto3" json:"received,omitempty"`
	SentRate             int64                `protobuf:"varint,10,opt,name=sentRate,proto3" json:"sentRate,omitempty"`
	ReceivedRate         int64                `protobuf:"varint,11,opt,name=receivedRate,proto3" json:"receivedRate,omitempty"`
	CaInfo               []*InfoResponse_Info `protobuf:"bytes,12,rep,name=caInfo,proto3" json:"caInfo,omitempty"`
	SaInfo               []*InfoResponse_Info `protobuf:"bytes,13,rep,name=saInfo,proto3" json:"saInfo,omitempty"`
	Err                  string               `protobuf:"bytes,14,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InfoResponse_Data) Reset()         { *m = InfoResponse_Data{} }
func (m *InfoResponse_Data) String() string { return proto.CompactTextString(m) }
func (*InfoResponse_Data) ProtoMessage()    {}
func (*InfoResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{5, 1}
}
func (m *InfoResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse_Data.Unmarshal(m, b)
}
func (m *InfoResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse_Data.Marshal(b, m, deterministic)
}
func (dst *InfoResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse_Data.Merge(dst, src)
}
func (m *InfoResponse_Data) XXX_Size() int {
	return xxx_messageInfo_InfoResponse_Data.Size(m)
}
func (m *InfoResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse_Data proto.InternalMessageInfo

func (m *InfoResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InfoResponse_Data) GetCname() string {
	if m != nil {
		return m.Cname
	}
	return ""
}

func (m *InfoResponse_Data) GetSname() string {
	if m != nil {
		return m.Sname
	}
	return ""
}

func (m *InfoResponse_Data) GetStatus() InfoResponse_Status {
	if m != nil {
		return m.Status
	}
	return InfoResponse_STOPPED
}

func (m *InfoResponse_Data) GetBindAddr() string {
	if m != nil {
		return m.BindAddr
	}
	return ""
}

func (m *InfoResponse_Data) GetBindPort() int32 {
	if m != nil {
		return m.BindPort
	}
	return 0
}

func (m *InfoResponse_Data) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *InfoResponse_Data) GetSent() int64 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *InfoResponse_Data) GetReceived() int64 {
	if m != nil {
		return m.Received
	}
	return 0
}

func (m *InfoResponse_Data) GetSentRate() int64 {
	if m != nil {
		return m.SentRate
	}
	return 0
}

func (m *InfoResponse_Data) GetReceivedRate() int64 {
	if m != nil {
		return m.ReceivedRate
	}
	return 0
}

func (m *InfoResponse_Data) GetCaInfo() []*InfoResponse_Info {
	if m != nil {
		return m.CaInfo
	}
	return nil
}

func (m *InfoResponse_Data) GetSaInfo() []*InfoResponse_Info {
	if m != nil {
		return m.SaInfo
	}
	return nil
}

func (m *InfoResponse_Data) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type ReloadResponse struct {
	Unchanged            []string `protobuf:"bytes,1,rep,name=unchanged,proto3" json:"unchanged,omitempty"`
	Added                []string `protobuf:"bytes,2,rep,name=added,proto3" json:"added,omitempty"`
	Deleted              []string `protobuf:"bytes,3,rep,name=deleted,proto3" json:"deleted,omitempty"`
	Updated              []string `protobuf:"bytes,4,rep,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReloadResponse) Reset()         { *m = ReloadResponse{} }
func (m *ReloadResponse) String() string { return proto.CompactTextString(m) }
func (*ReloadResponse) ProtoMessage()    {}
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{6}
}
func (m *ReloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReloadResponse.Unmarshal(m, b)
}
func (m *ReloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReloadResponse.Marshal(b, m, deterministic)
}
func (dst *ReloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReloadResponse.Merge(dst, src)
}
func (m *ReloadResponse) XXX_Size() int {
	return xxx_messageInfo_ReloadResponse.Size(m)
}
func (m *ReloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReloadResponse proto.InternalMessageInfo

func (m *ReloadResponse) GetUnchanged() []string {
	if m != nil {
		return m.Unchanged
	}
	return nil
}

func (m *ReloadResponse) GetAdded() []string {
	if m != nil {
		return m.Added
	}
	return nil
}

func (m *ReloadResponse) GetDeleted() []string {
	if m != nil {
		return m.Deleted
	}
	return nil
}

func (m *ReloadResponse) GetUpdated() []string {
	if m != nil {
		return m.Updated
	}
	return nil
}

type QuitResponse struct {
	Status               QuitResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.QuitResponse_Status" json:"status,omitempty"`
	Pid                  uint32              `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QuitResponse) Reset()         { *m = QuitResponse{} }
func (m *QuitResponse) String() string { return proto.CompactTextString(m) }
func (*QuitResponse) ProtoMessage()    {}
func (*QuitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{7}
}
func (m *QuitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitResponse.Unmarshal(m, b)
}
func (m *QuitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitResponse.Marshal(b, m, deterministic)
}
func (dst *QuitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitResponse.Merge(dst, src)
}
func (m *QuitResponse) XXX_Size() int {
	return xxx_messageInfo_QuitResponse.Size(m)
}
func (m *QuitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuitResponse proto.InternalMessageInfo

func (m *QuitResponse) GetStatus() QuitResponse_Status {
	if m != nil {
		return m.Status
	}
	return QuitResponse_QUITED
}

func (m *QuitResponse) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

type ClearCacheResponse struct {
	Status               ClearCacheResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.ClearCacheResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ClearCacheResponse) Reset()         { *m = ClearCacheResponse{} }
func (m *ClearCacheResponse) String() string { return proto.CompactTextString(m) }
func (*ClearCacheResponse) ProtoMessage()    {}
func (*ClearCacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{8}
}
func (m *ClearCacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearCacheResponse.Unmarshal(m, b)
}
func (m *ClearCacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearCacheResponse.Marshal(b, m, deterministic)
}
func (dst *ClearCacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearCacheResponse.Merge(dst, src)
}
func (m *ClearCacheResponse) XXX_Size() int {
	return xxx_messageInfo_ClearCacheResponse.Size(m)
}
func (m *ClearCacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearCacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClearCacheResponse proto.InternalMessageInfo

func (m *ClearCacheResponse) GetStatus() ClearCacheResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClearCacheResponse_SUCCESS
}

type ListResponse struct {
	Status               ListResponse_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=rpc.ListResponse_Status" json:"status,omitempty"`
	Data                 []*ListResponse_Data `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{9}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetStatus() ListResponse_Status {
	if m != nil {
		return m.Status
	}
	return ListResponse_SUCCESS
}

func (m *ListResponse) GetData() []*ListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResponse_Data struct {
	Name                 string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain                []*ListResponse_Data_Chain `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListResponse_Data) Reset()         { *m = ListResponse_Data{} }
func (m *ListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ListResponse_Data) ProtoMessage()    {}
func (*ListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{9, 0}
}
func (m *ListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse_Data.Unmarshal(m, b)
}
func (m *ListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse_Data.Marshal(b, m, deterministic)
}
func (dst *ListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse_Data.Merge(dst, src)
}
func (m *ListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ListResponse_Data.Size(m)
}
func (m *ListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse_Data proto.InternalMessageInfo

func (m *ListResponse_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListResponse_Data) GetChain() []*ListResponse_Data_Chain {
	if m != nil {
		return m.Chain
	}
	return nil
}

type ListResponse_Data_Chain struct {
	ClientAddr           string   `protobuf:"bytes,1,opt,name=clientAddr,proto3" json:"clientAddr,omitempty"`
	RemoteAddr           string   `protobuf:"bytes,2,opt,name=remoteAddr,proto3" json:"remoteAddr,omitempty"`
	ConnectedTime        int64    `protobuf:"varint,3,opt,name=connectedTime,proto3" json:"connectedTime,omitempty"`
	ClosedTime           int64    `protobuf:"varint,4,opt,name=closedTime,proto3" json:"closedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse_Data_Chain) Reset()         { *m = ListResponse_Data_Chain{} }
func (m *ListResponse_Data_Chain) String() string { return proto.CompactTextString(m) }
func (*ListResponse_Data_Chain) ProtoMessage()    {}
func (*ListResponse_Data_Chain) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{9, 0, 0}
}
func (m *ListResponse_Data_Chain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse_Data_Chain.Unmarshal(m, b)
}
func (m *ListResponse_Data_Chain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse_Data_Chain.Marshal(b, m, deterministic)
}
func (dst *ListResponse_Data_Chain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse_Data_Chain.Merge(dst, src)
}
func (m *ListResponse_Data_Chain) XXX_Size() int {
	return xxx_messageInfo_ListResponse_Data_Chain.Size(m)
}
func (m *ListResponse_Data_Chain) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse_Data_Chain.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse_Data_Chain proto.InternalMessageInfo

func (m *ListResponse_Data_Chain) GetClientAddr() string {
	if m != nil {
		return m.ClientAddr
	}
	return ""
}

func (m *ListResponse_Data_Chain) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *ListResponse_Data_Chain) GetConnectedTime() int64 {
	if m != nil {
		return m.ConnectedTime
	}
	return 0
}

func (m *ListResponse_Data_Chain) GetClosedTime() int64 {
	if m != nil {
		return m.ClosedTime
	}
	return 0
}

type Response struct {
	Type                 RequestType         `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.RequestType" json:"type,omitempty"`
	Err                  *Error              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	Auth                 *AuthResponse       `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Status               *StatusResponse     `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Start                *StartResponse      `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 *StopResponse       `protobuf:"bytes,6,opt,name=stop,proto3" json:"stop,omitempty"`
	Info                 *InfoResponse       `protobuf:"bytes,7,opt,name=info,proto3" json:"info,omitempty"`
	Reload               *ReloadResponse     `protobuf:"bytes,8,opt,name=reload,proto3" json:"reload,omitempty"`
	Quit                 *QuitResponse       `protobuf:"bytes,9,opt,name=quit,proto3" json:"quit,omitempty"`
	Clear                *ClearCacheResponse `protobuf:"bytes,10,opt,name=clear,proto3" json:"clear,omitempty"`
	List                 *ListResponse       `protobuf:"bytes,11,opt,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_response_8ab824084549083a, []int{10}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_AUTH
}

func (m *Response) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func (m *Response) GetAuth() *AuthResponse {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Response) GetStatus() *StatusResponse {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Response) GetStart() *StartResponse {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Response) GetStop() *StopResponse {
	if m != nil {
		return m.Stop
	}
	return nil
}

func (m *Response) GetInfo() *InfoResponse {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Response) GetReload() *ReloadResponse {
	if m != nil {
		return m.Reload
	}
	return nil
}

func (m *Response) GetQuit() *QuitResponse {
	if m != nil {
		return m.Quit
	}
	return nil
}

func (m *Response) GetClear() *ClearCacheResponse {
	if m != nil {
		return m.Clear
	}
	return nil
}

func (m *Response) GetList() *ListResponse {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "rpc.Error")
	proto.RegisterType((*AuthResponse)(nil), "rpc.AuthResponse")
	proto.RegisterType((*StatusResponse)(nil), "rpc.StatusResponse")
	proto.RegisterType((*StatusResponse_Data)(nil), "rpc.StatusResponse.Data")
	proto.RegisterType((*StartResponse)(nil), "rpc.StartResponse")
	proto.RegisterType((*StartResponse_Data)(nil), "rpc.StartResponse.Data")
	proto.RegisterType((*StopResponse)(nil), "rpc.StopResponse")
	proto.RegisterType((*StopResponse_Data)(nil), "rpc.StopResponse.Data")
	proto.RegisterType((*InfoResponse)(nil), "rpc.InfoResponse")
	proto.RegisterType((*InfoResponse_Info)(nil), "rpc.InfoResponse.Info")
	proto.RegisterType((*InfoResponse_Data)(nil), "rpc.InfoResponse.Data")
	proto.RegisterType((*ReloadResponse)(nil), "rpc.ReloadResponse")
	proto.RegisterType((*QuitResponse)(nil), "rpc.QuitResponse")
	proto.RegisterType((*ClearCacheResponse)(nil), "rpc.ClearCacheResponse")
	proto.RegisterType((*ListResponse)(nil), "rpc.ListResponse")
	proto.RegisterType((*ListResponse_Data)(nil), "rpc.ListResponse.Data")
	proto.RegisterType((*ListResponse_Data_Chain)(nil), "rpc.ListResponse.Data.Chain")
	proto.RegisterType((*Response)(nil), "rpc.Response")
	proto.RegisterEnum("rpc.AuthResponse_Status", AuthResponse_Status_name, AuthResponse_Status_value)
	proto.RegisterEnum("rpc.StatusResponse_Status", StatusResponse_Status_name, StatusResponse_Status_value)
	proto.RegisterEnum("rpc.StartResponse_Status", StartResponse_Status_name, StartResponse_Status_value)
	proto.RegisterEnum("rpc.StopResponse_Status", StopResponse_Status_name, StopResponse_Status_value)
	proto.RegisterEnum("rpc.InfoResponse_Status", InfoResponse_Status_name, InfoResponse_Status_value)
	proto.RegisterEnum("rpc.QuitResponse_Status", QuitResponse_Status_name, QuitResponse_Status_value)
	proto.RegisterEnum("rpc.ClearCacheResponse_Status", ClearCacheResponse_Status_name, ClearCacheResponse_Status_value)
	proto.RegisterEnum("rpc.ListResponse_Status", ListResponse_Status_name, ListResponse_Status_value)
}

func init() {
	proto.RegisterFile("src/skywalker/rpc/response.proto", fileDescriptor_response_8ab824084549083a)
}

var fileDescriptor_response_8ab824084549083a = []byte{
	// 958 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0xb1, 0x9d, 0x36, 0x27, 0x49, 0x15, 0x86, 0x3f, 0x6f, 0x54, 0xed, 0x46, 0xd6, 0x22,
	0x45, 0x2c, 0x9b, 0x96, 0x20, 0x71, 0x5f, 0x65, 0x03, 0xaa, 0xb4, 0xea, 0x76, 0x27, 0xcd, 0x2d,
	0x68, 0xd6, 0x1e, 0x36, 0x56, 0x13, 0xdb, 0x3b, 0x1e, 0x2f, 0xe4, 0x21, 0x78, 0x17, 0x1e, 0x82,
	0x3b, 0x7a, 0xc5, 0x03, 0x70, 0x81, 0x78, 0x10, 0x34, 0x67, 0x6c, 0x67, 0x9c, 0xa4, 0xa9, 0x84,
	0x10, 0x77, 0x39, 0xe7, 0xfb, 0x72, 0x66, 0xbe, 0x33, 0xf3, 0x9d, 0x31, 0x0c, 0x32, 0x11, 0x9c,
	0x65, 0xb7, 0xeb, 0x9f, 0xd8, 0xf2, 0x96, 0x8b, 0x33, 0x91, 0x06, 0x67, 0x82, 0x67, 0x69, 0x12,
	0x67, 0x7c, 0x94, 0x8a, 0x44, 0x26, 0xc4, 0x16, 0x69, 0xd0, 0x7f, 0xb2, 0x8f, 0xf6, 0x2e, 0xe7,
	0x99, 0xd4, 0x2c, 0xff, 0x11, 0xb8, 0x53, 0x21, 0x12, 0x41, 0x7a, 0x60, 0xaf, 0xb2, 0xb7, 0x9e,
	0x35, 0xb0, 0x86, 0x2d, 0xaa, 0x7e, 0xfa, 0x21, 0x74, 0x2e, 0x72, 0xb9, 0xa0, 0x45, 0x59, 0x72,
	0x0e, 0xcd, 0x4c, 0x32, 0x99, 0x67, 0x48, 0x3a, 0x19, 0x7b, 0x23, 0x91, 0x06, 0x23, 0x93, 0x32,
	0x9a, 0x21, 0x4e, 0x0b, 0x9e, 0xef, 0x43, 0x53, 0x67, 0x48, 0x1b, 0x8e, 0x66, 0xf3, 0xc9, 0x64,
	0x3a, 0x9b, 0xf5, 0x3e, 0x50, 0xc1, 0xb7, 0x17, 0x97, 0x2f, 0xe7, 0x74, 0xda, 0xb3, 0xfc, 0x3f,
	0x1a, 0x70, 0x52, 0xfc, 0xad, 0x5c, 0xe8, 0x4b, 0x70, 0x42, 0x26, 0x99, 0x67, 0x0d, 0xec, 0x61,
	0xbb, 0x58, 0xa6, 0x4e, 0x19, 0xbd, 0x60, 0x92, 0x51, 0x64, 0xf5, 0xff, 0xb2, 0xc0, 0x51, 0x21,
	0x21, 0xe0, 0xc4, 0x6c, 0xc5, 0x0b, 0x09, 0xf8, 0x9b, 0x7c, 0x0c, 0x6e, 0x80, 0xc9, 0x06, 0x26,
	0x75, 0xa0, 0xb2, 0x19, 0x66, 0x6d, 0x9d, 0xc5, 0x80, 0x8c, 0x2b, 0x7d, 0x0e, 0xea, 0xeb, 0xef,
	0x5b, 0xb8, 0xae, 0x90, 0xf4, 0xe1, 0xf8, 0x4d, 0x14, 0x87, 0x17, 0x61, 0x28, 0x3c, 0x17, 0x8b,
	0x55, 0x71, 0x89, 0x5d, 0x27, 0x42, 0x7a, 0xcd, 0x81, 0x35, 0x74, 0x69, 0x15, 0x93, 0x53, 0x68,
	0x65, 0x92, 0x09, 0x79, 0x13, 0xad, 0xb8, 0x77, 0x34, 0xb0, 0x86, 0x36, 0xdd, 0x24, 0xd4, 0x59,
	0x70, 0x21, 0xbc, 0x63, 0x7d, 0x16, 0x5c, 0x08, 0xff, 0x79, 0xad, 0x93, 0x37, 0xaf, 0xae, 0xaf,
	0xa7, 0x2f, 0x74, 0x27, 0xe9, 0xfc, 0xea, 0xea, 0xf2, 0xea, 0xbb, 0x9e, 0x45, 0x5a, 0xe0, 0x4e,
	0x29, 0x7d, 0x45, 0x7b, 0x0d, 0xff, 0xce, 0x82, 0xee, 0x4c, 0x95, 0xab, 0x7a, 0xfa, 0xac, 0xd6,
	0xd3, 0xcf, 0x4a, 0x69, 0x1b, 0x86, 0xd9, 0xd2, 0x1f, 0x0e, 0x74, 0xf4, 0xab, 0xaa, 0x4b, 0x0d,
	0xec, 0xd2, 0xa3, 0x3d, 0xa5, 0xb6, 0x9a, 0x54, 0xc8, 0xb1, 0xef, 0x95, 0x73, 0x41, 0x6f, 0x50,
	0x4e, 0xa5, 0xc0, 0x32, 0x95, 0x35, 0xfc, 0xdf, 0x2d, 0xe8, 0xcc, 0x64, 0x92, 0x56, 0x6a, 0xbe,
	0xa8, 0xa9, 0xf9, 0xb4, 0xd8, 0xc2, 0x86, 0x60, 0x8a, 0xf9, 0xfe, 0x80, 0x98, 0xf3, 0x2d, 0x31,
	0xde, 0x6e, 0xa5, 0x07, 0xb5, 0x9c, 0xed, 0x3f, 0x1a, 0x43, 0x4b, 0x17, 0x5a, 0xf3, 0xab, 0x8d,
	0x9a, 0x3b, 0x07, 0x3a, 0x97, 0xf1, 0x8f, 0xc9, 0x41, 0x35, 0x26, 0xc1, 0x54, 0x33, 0x02, 0x47,
	0x41, 0x6a, 0x1f, 0xb7, 0x7c, 0x5d, 0xda, 0xf5, 0x96, 0xaf, 0xd5, 0xa5, 0x7e, 0xcf, 0x96, 0x79,
	0x75, 0xd5, 0x31, 0xe8, 0xff, 0x6a, 0xff, 0x47, 0xee, 0x38, 0xdf, 0x72, 0x87, 0xb7, 0xbb, 0xcd,
	0xff, 0xc5, 0x1b, 0x04, 0x9c, 0x8c, 0xc7, 0x12, 0xcd, 0x61, 0x53, 0xfc, 0xad, 0xaa, 0x09, 0x1e,
	0xf0, 0xe8, 0x3d, 0x0f, 0xbd, 0x16, 0xe6, 0xab, 0x58, 0x61, 0x8a, 0x43, 0x99, 0xe4, 0x1e, 0x68,
	0xac, 0x8c, 0x89, 0x0f, 0x9d, 0x92, 0x87, 0x78, 0x1b, 0xf1, 0x5a, 0x8e, 0x8c, 0xa0, 0x19, 0x30,
	0x25, 0xd3, 0xeb, 0xdc, 0x77, 0x3c, 0x18, 0x14, 0x2c, 0xc5, 0xcf, 0x34, 0xbf, 0x7b, 0x98, 0xaf,
	0x59, 0xe5, 0x85, 0x3a, 0xf9, 0xd7, 0x5e, 0xff, 0x19, 0x4e, 0x28, 0x5f, 0x26, 0x2c, 0xac, 0xee,
	0xd3, 0x29, 0xb4, 0xf2, 0x38, 0x58, 0xb0, 0xf8, 0x2d, 0x0f, 0xf1, 0x52, 0xb5, 0xe8, 0x26, 0xa1,
	0x8e, 0x97, 0x85, 0x21, 0x0f, 0xbd, 0x06, 0x22, 0x3a, 0x20, 0x1e, 0x1c, 0x85, 0x7c, 0xc9, 0x25,
	0x0f, 0x3d, 0x1b, 0xf3, 0x65, 0xa8, 0x90, 0x3c, 0x0d, 0x99, 0x42, 0x1c, 0x8d, 0x14, 0xa1, 0x9f,
	0x41, 0xe7, 0x75, 0x1e, 0xc9, 0x07, 0x1e, 0x08, 0x93, 0xb2, 0xc7, 0x4d, 0x69, 0x14, 0xe2, 0xf5,
	0xeb, 0x52, 0xf5, 0xd3, 0x7f, 0x52, 0x89, 0x07, 0x68, 0xbe, 0x9e, 0x5f, 0x6e, 0x0f, 0x06, 0x3f,
	0x00, 0x32, 0x59, 0x72, 0x26, 0x26, 0x2c, 0x58, 0xf0, 0x6a, 0xe9, 0x6f, 0xb6, 0x96, 0x7e, 0x8c,
	0x4b, 0xef, 0x12, 0xb7, 0x5f, 0xa8, 0x4f, 0xf6, 0xbe, 0x50, 0xfe, 0xdf, 0x0d, 0xe8, 0xbc, 0x8c,
	0xb2, 0x87, 0xa4, 0x99, 0x94, 0x6d, 0x69, 0xa5, 0xa9, 0x1b, 0xc6, 0x2d, 0xa8, 0xf1, 0x0d, 0x53,
	0xff, 0x79, 0xe8, 0x09, 0x1b, 0x83, 0x1b, 0x2c, 0x58, 0x14, 0x17, 0x95, 0x4e, 0xf7, 0x57, 0x1a,
	0x4d, 0x14, 0x87, 0x6a, 0x6a, 0xff, 0x17, 0x0b, 0x5c, 0x4c, 0x90, 0xc7, 0x00, 0xc1, 0x32, 0xe2,
	0xb1, 0x44, 0x1b, 0xea, 0xba, 0x46, 0x46, 0xe1, 0x82, 0xaf, 0x12, 0xc9, 0x11, 0xd7, 0x73, 0xc0,
	0xc8, 0x90, 0xa7, 0xd0, 0x0d, 0x92, 0x38, 0xe6, 0x81, 0xe4, 0x21, 0x1a, 0xd2, 0x46, 0x8f, 0xd4,
	0x93, 0x7a, 0x95, 0x24, 0x2b, 0x28, 0x0e, 0x52, 0x8c, 0xcc, 0x7d, 0x6d, 0xfe, 0xcd, 0x86, 0xe3,
	0xaa, 0xc5, 0x4f, 0xc1, 0x91, 0xeb, 0x94, 0x17, 0x0d, 0xee, 0xa1, 0x4c, 0xaa, 0xbf, 0x55, 0x6e,
	0xd6, 0x29, 0xa7, 0x88, 0x92, 0x53, 0x6d, 0x17, 0xb5, 0xd1, 0xf6, 0x18, 0x90, 0x84, 0xdf, 0x2f,
	0x68, 0x1d, 0xf2, 0x39, 0x38, 0x2c, 0x97, 0x0b, 0xdc, 0x64, 0x7b, 0xfc, 0xe1, 0xce, 0x07, 0x0a,
	0x45, 0x98, 0x3c, 0xab, 0xcd, 0xb2, 0xf6, 0xf8, 0xa3, 0x3d, 0x2f, 0x7d, 0x75, 0x90, 0x43, 0x70,
	0x71, 0xfa, 0xe0, 0x0c, 0x6b, 0x8f, 0xc9, 0xee, 0x7b, 0x47, 0x35, 0x41, 0xad, 0x9e, 0xc9, 0x24,
	0xc5, 0x81, 0x56, 0xae, 0x6e, 0xbe, 0x25, 0x14, 0x61, 0x45, 0x8b, 0xd4, 0x7c, 0x38, 0x32, 0x68,
	0xe6, 0x7c, 0xa0, 0x08, 0xab, 0x4d, 0x0a, 0xf4, 0x35, 0x8e, 0xba, 0x72, 0x93, 0x75, 0xab, 0xd3,
	0x82, 0xa2, 0x6a, 0xbe, 0xcb, 0x23, 0x89, 0xd3, 0xaf, 0xac, 0x69, 0x1a, 0x8f, 0x22, 0x4c, 0x9e,
	0x83, 0x1b, 0x28, 0x4f, 0xe0, 0x24, 0x2c, 0x3f, 0x03, 0x76, 0x5d, 0x42, 0x35, 0x4b, 0x55, 0x5d,
	0x46, 0x99, 0xc4, 0xb9, 0x58, 0x56, 0x35, 0x6f, 0x1e, 0x45, 0xf8, 0x4d, 0x13, 0x3f, 0x25, 0xbf,
	0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x4b, 0x65, 0xbe, 0x94, 0x0a, 0x00, 0x00,
}
